### ISSUE TITLE
The script crashes with an error

### ISSUE THREAD

**Issue by mudachyo** [ClementRoyer/TwitchAFK#15]
**How to fix it?**
![image](https://user-images.githubusercontent.com/25475399/103321384-753e8900-4a4a-11eb-851b-d87f4bff43f4.png)

**Comment by ClementRoyer** [comment]
Twitch changed how they display coins in the bet menu, I need to update this.

**Comment by mudachyo** [comment]
Understood, I will wait

**Comment by ClementRoyer** [comment]
Fixed by [024838b ](https://github.com/ClementRoyer/TwitchAutoCollect-AutoBet/commit/024838b153cb85d5b7d7cd339a613db3f0807caa)

Feel free to report any other bugs you have!
