### ISSUE TITLE
could not convert coins string to float: '1.1tys'

### ISSUE THREAD

**Issue by Piteriuz** [ClementRoyer/TwitchAFK#17]
In other language than english - for example in Polish i received ValueError when i collect more than 1000 coins, because Twitch always shorten '1000' for '1tys' in my language.
![dGK6fRj](https://user-images.githubusercontent.com/6289528/104388653-df225c80-5539-11eb-81c4-9d57e7d77e2d.png)
and screenshoot from Twitch:
![VoIiBtB](https://user-images.githubusercontent.com/6289528/104388641-d3369a80-5539-11eb-880b-01c7424ddb18.png)
maybe could you collect 'skulls' value instead of discovered value

**Comment by ClementRoyer** [comment]
I'm looking closely at this.

I need to find another way to get channel points in a near future (using graphQL for example) but for now and just for a hotfix can you give me the Twitch polish equivalent for "K", "M", "B' (k = thousand, Million, Billion) please ?

**Comment by ClementRoyer** [comment]
I can't collect "Skulls" because it only appears on the HTML when you are over the text, which creates a new div at the end of the HTML file.

**Comment by ClementRoyer** [comment]
I have implemented a patch with GraphMQ on my local machine, will test it a bit more tomorrow when I have a better internet.

**Comment by Piteriuz** [comment]
K - tys
M - mil
B - bil

>can you give me the Twitch polish equivalent for "K", "M", "B' (k = thousand, Million, Billion) please ?

**Comment by ClementRoyer** [comment]
You can try to use the branch "dev". It should patch the issue, but I can't test due to connection issue.

**Comment by Piteriuz** [comment]
> You can try to use the branch "dev". It should patch the issue, but I can't test due to connection issue.

In the first you should add to requirement.txt file the new line `requests`
By 'dev' branch i can't collect coins. I removed cookies and generate new one auth and this happening again.
![1111111111111111111](https://user-images.githubusercontent.com/6289528/104584164-6d91fd80-5662-11eb-9d38-8b19e740f5c7.png)

**Comment by ClementRoyer** [comment]
Should work now with lastest commit on master.
